/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutRecoverRequestRouteImport } from './routes/_layout/recover/request'
import { Route as LayoutRankingClaimRouteImport } from './routes/_layout/ranking/claim'
import { Route as LayoutRankingRankingIdIndexRouteImport } from './routes/_layout/ranking/$rankingId/index'
import { Route as LayoutRecoverConsumeTokenRouteImport } from './routes/_layout/recover/consume/$token'
import { Route as LayoutRankingRankingIdEditRouteImport } from './routes/_layout/ranking/$rankingId/edit'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecoverRequestRoute = LayoutRecoverRequestRouteImport.update({
  id: '/recover/request',
  path: '/recover/request',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRankingClaimRoute = LayoutRankingClaimRouteImport.update({
  id: '/ranking/claim',
  path: '/ranking/claim',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRankingRankingIdIndexRoute =
  LayoutRankingRankingIdIndexRouteImport.update({
    id: '/ranking/$rankingId/',
    path: '/ranking/$rankingId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutRecoverConsumeTokenRoute =
  LayoutRecoverConsumeTokenRouteImport.update({
    id: '/recover/consume/$token',
    path: '/recover/consume/$token',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutRankingRankingIdEditRoute =
  LayoutRankingRankingIdEditRouteImport.update({
    id: '/ranking/$rankingId/edit',
    path: '/ranking/$rankingId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/ranking/claim': typeof LayoutRankingClaimRoute
  '/recover/request': typeof LayoutRecoverRequestRoute
  '/ranking/$rankingId/edit': typeof LayoutRankingRankingIdEditRoute
  '/recover/consume/$token': typeof LayoutRecoverConsumeTokenRoute
  '/ranking/$rankingId/': typeof LayoutRankingRankingIdIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof LayoutAboutRoute
  '/': typeof LayoutIndexRoute
  '/ranking/claim': typeof LayoutRankingClaimRoute
  '/recover/request': typeof LayoutRecoverRequestRoute
  '/ranking/$rankingId/edit': typeof LayoutRankingRankingIdEditRoute
  '/recover/consume/$token': typeof LayoutRecoverConsumeTokenRoute
  '/ranking/$rankingId': typeof LayoutRankingRankingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/ranking/claim': typeof LayoutRankingClaimRoute
  '/_layout/recover/request': typeof LayoutRecoverRequestRoute
  '/_layout/ranking/$rankingId/edit': typeof LayoutRankingRankingIdEditRoute
  '/_layout/recover/consume/$token': typeof LayoutRecoverConsumeTokenRoute
  '/_layout/ranking/$rankingId/': typeof LayoutRankingRankingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ranking/claim'
    | '/recover/request'
    | '/ranking/$rankingId/edit'
    | '/recover/consume/$token'
    | '/ranking/$rankingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/'
    | '/ranking/claim'
    | '/recover/request'
    | '/ranking/$rankingId/edit'
    | '/recover/consume/$token'
    | '/ranking/$rankingId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/about'
    | '/_layout/'
    | '/_layout/ranking/claim'
    | '/_layout/recover/request'
    | '/_layout/ranking/$rankingId/edit'
    | '/_layout/recover/consume/$token'
    | '/_layout/ranking/$rankingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recover/request': {
      id: '/_layout/recover/request'
      path: '/recover/request'
      fullPath: '/recover/request'
      preLoaderRoute: typeof LayoutRecoverRequestRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ranking/claim': {
      id: '/_layout/ranking/claim'
      path: '/ranking/claim'
      fullPath: '/ranking/claim'
      preLoaderRoute: typeof LayoutRankingClaimRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ranking/$rankingId/': {
      id: '/_layout/ranking/$rankingId/'
      path: '/ranking/$rankingId'
      fullPath: '/ranking/$rankingId/'
      preLoaderRoute: typeof LayoutRankingRankingIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recover/consume/$token': {
      id: '/_layout/recover/consume/$token'
      path: '/recover/consume/$token'
      fullPath: '/recover/consume/$token'
      preLoaderRoute: typeof LayoutRecoverConsumeTokenRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ranking/$rankingId/edit': {
      id: '/_layout/ranking/$rankingId/edit'
      path: '/ranking/$rankingId/edit'
      fullPath: '/ranking/$rankingId/edit'
      preLoaderRoute: typeof LayoutRankingRankingIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutRankingClaimRoute: typeof LayoutRankingClaimRoute
  LayoutRecoverRequestRoute: typeof LayoutRecoverRequestRoute
  LayoutRankingRankingIdEditRoute: typeof LayoutRankingRankingIdEditRoute
  LayoutRecoverConsumeTokenRoute: typeof LayoutRecoverConsumeTokenRoute
  LayoutRankingRankingIdIndexRoute: typeof LayoutRankingRankingIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutRankingClaimRoute: LayoutRankingClaimRoute,
  LayoutRecoverRequestRoute: LayoutRecoverRequestRoute,
  LayoutRankingRankingIdEditRoute: LayoutRankingRankingIdEditRoute,
  LayoutRecoverConsumeTokenRoute: LayoutRecoverConsumeTokenRoute,
  LayoutRankingRankingIdIndexRoute: LayoutRankingRankingIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
